name: Threat Modeling
on: [push, pull_request, workflow_dispatch]

jobs:
  threat-model:
    runs-on: ubuntu-latest
    steps:
      - name: Use CI Threat Modeler
        id: itsa
        uses: harshsoni-harsh/threat-modeler@main
